version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 875525659788.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t ia .
      - docker tag ia:latest 875525659788.dkr.ecr.us-east-1.amazonaws.com/ia:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 875525659788.dkr.ecr.us-east-1.amazonaws.com/ia:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ia-container","imageUri":"875525659788.dkr.ecr.us-east-1.amazonaws.com/ia:latest"}]' 875525659788.dkr.ecr.us-east-1.amazonaws.com/ia:latest > imagedefinitions1.json 
artifacts:
    files:
        - imagedefinitions1.json
